### ISSUE TITLE
Reverse ProGuard jar and mappings?

### ISSUE THREAD

**Issue by mat-ej** [LPK-Matt/SkidSuite2#3]
Hello, thanks for your help with my previous issue. Everything working well :) You did an amazing job with this tool.

I am really sorry to bother, I understand you are busy. IRL(So whenever you have time, I am in no hurry).

Could you please point me to a right direction how to deal with deobfuscating "ProGuard" .apks ? I found your mapping utility, but I seem to lack the knowledge what exactly is the mappings file that should be included for ProGuard reverse utility. I'd be very thankful for any help or resources, articles on how to do this properly.

Thank you and have a nice day :)

**Comment by LPK-Matt** [comment]
It's not bothersome.

The intention behind the design was that you would have the mappings file that was generated along-side the jar file _(dexToJar the APK to get the jar)_ that was obfuscated.

For example if obfuscate proguard with itself and print the mapping file it will make the following mapping structure for each class:
```
proguard.ClassPath -> proguard.c:
    java.util.List classPathEntries -> c
    void <init>() -> <init>
    boolean hasOutput() -> b
    void clear() -> clear
    void add(int,proguard.ClassPathEntry) -> a
    boolean add(proguard.ClassPathEntry) -> a
    boolean addAll(proguard.ClassPath) -> a
    proguard.ClassPathEntry get(int) -> a
    proguard.ClassPathEntry remove(int) -> b
    boolean isEmpty() -> isEmpty
    int size() -> size
```

The syntax is:
```
BeforeName -> AfterName
    Type BeforeFieldName -> AfterFieldName
    Type BeforeMethodName+TypeDescriptor -> AfterMethodName
```

Since you would have all the before and after information getting the original names back would be easy. However if you don't have the mappings file your only real option is to make your own. It wouldn't have to be complete, you could even only map out a single class if you felt like it. 

As for actually mapping out classes this is a tedious process. If you don't have the source to a program and want to understand how it works through obfuscation you're going to have to do a bit of debugging and source diving. You could manually create a mappings file based on your discoveries and feed that into the mapping reverser. Personally I like the enigma format as it's easier to make with [Cuchaz's Enigma](https://www.cuchazinteractive.com/enigma/) and is easy to write by hand.

Here's an example:
```
CLASS org/objectweb/asm/tree/InvokeDynamicInsnNode Bk
	FIELD name A Ljava/lang/String;
	FIELD desc C Ljava/lang/String;
	FIELD bsm A Lorg/objectweb/asm/Handle;
	FIELD bsmArgs A [Ljava/lang/Object;
	METHOD <init> <init> (Ljava/lang/String;Ljava/lang/String;Lorg/objectweb/asm/Handle;[Ljava/lang/Object;)V
	METHOD getType G ()I
	METHOD accept D (Lorg/objectweb/asm/MethodVisitor;)V
	METHOD clone clone (Ljava/util/Map;)Lorg/objectweb/asm/tree/AbstractInsnNode;
```

The syntax is:
```
CLASS BeforeName AfterName
	FIELD BeforeName AfterName TypeDescriptor
	Method BeforeName AfterName TypeDescriptor
```
